# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingModel',
            fields=[
                ('at_datetime', models.DateTimeField(verbose_name='Linux AT start time')),
                ('unix_jobid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Job ID')),
                ('specrec_args_length', models.IntegerField()),
                ('specrec_args_freq', models.IntegerField()),
                ('specrec_args_sample_rate', models.IntegerField()),
                ('specrec_args_start', models.DateTimeField(verbose_name='Specrec begin recording time')),
                ('specrec_args_full_commands', models.CharField(max_length=1000)),
                ('local_path', models.CharField(max_length=1000)),
                ('backup_path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RFSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RFSN DEFAULT', max_length=200)),
                ('hostname', models.CharField(max_length=500)),
                ('port', models.IntegerField(default=5035)),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SESSION DEFAULT', max_length=100)),
                ('log_path', models.CharField(max_length=100)),
                ('starting_path', models.CharField(max_length=100)),
                ('sample_rate', models.IntegerField()),
                ('start_early', models.IntegerField()),
                ('rfsns', models.ManyToManyField(to='myapp.RFSN')),
            ],
        ),
        migrations.AddField(
            model_name='recordingmodel',
            name='rfsn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RFSN'),
        ),
        migrations.AddField(
            model_name='recordingmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.SessionModel'),
        ),
    ]
