# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingmodel',
            name='specrec_args_gain',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
