# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160402_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='filename',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='specrec_args',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Specrec launch time'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='unix_jobid',
            field=models.IntegerField(verbose_name='Job ID'),
        ),
    ]
