# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name=b'Specrec launch time')),
                ('unix_jobid', models.IntegerField(verbose_name=b'Job ID')),
                ('specrec_args', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rfsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='epoch',
            name='rfsn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Rfsn'),
        ),
    ]
